INPUT_HINTS = {
    'list_of_numbers': 'Введите числа в формате:',
    'lists': 'Введите списки в формате:',
    'list_and_number': 'Введите список и число в формате:',
    'list_of_words': 'Введите слова в формате:',
    'words_and_numbers': 'Введите слова и числа в формате:',
}

TASKS = {
    1: {'description': 'Удалить дубликаты из списка, сохранив порядок.',
        'example': '[3, 2, 2, 1, 5, 3] → [3, 2, 1, 5]',
        'type': 'list_of_numbers',},
    2: {'description': 'Найти сумму всех чётных чисел в списке.',
        'example': '[1, 2, 3, 4, 5, 6] → 12',
        'type': 'list_of_numbers',},
    3: {'description': 'Развернуть список (в порядке обратном исходному).',
        'example': '[1, 2, 3, 4, 5] → [5, 4, 3, 2, 1]',
        'type': 'list_of_numbers',},
    4: {'description': 'Найти максимальный элемент в списке, не используя max()',
        'example': '[10, 3, 5, 6, 9, 8] → 10',
        'type': 'list_of_numbers',},
    5: {'description': 'Объединить два списка в один, удалив повторяющиеся элементы.',
        'example': '[1, 2, 3] [3, 4, 5] → [1, 2, 3, 4, 5]',
        'type': 'lists',},
    6: {'description': 'Проверить, отсортирован ли список по возрастанию.',
        'example': '\n[1, 2, 3] → ✅ Список сортирован\n[3, 2, 1] → ❌ Список не сортирован',
        'type': 'list_of_numbers',},
    7: {'description': 'Вставить число в список на позицию, равную его значению.',
        'example': '[10, 20, 30]; 2 → [10, 20, 2, 30]',
        'type': 'list_and_number',},
    8: {'description': 'Удалить первое вхождение минимального элемента из списка.',
        'example': '[5, 3, 2, 8, 2, 10] → [5, 3, 8, 2, 10]',
        'type': 'list_of_numbers',},
    9: {'description': 'Сложить стоящие по соседству числа.',
        'example': '[1, 2, 3, 4] → [2, 4, 6, 3];\nобъяснение: [2, 1+3=4, 2+4=6, 3]',
        'type': 'list_of_numbers'},
    10: {'description': 'Переместить нули в конец списка.',
         'example': '[0, 1, 0, 3, 12] → [1, 3, 12, 0, 0]',
         'type': 'list_of_numbers'},
    11: {'description': 'Объединить списки в кортеж.',
         'example': "['Alice', 'Bob', 'Charlie'] [25, 30, 28] → [(Alice, 25), (Bob, 30), (Charlie, 28)]",
         'type': 'words_and_numbers'},
    12: {'description': 'Найти элемент списка, который встречается чаще всего.',
         'example': "['apple', 'banana', 'apple', 'orange', 'banana', 'apple'] → apple",
         'type': 'list_of_words'},
    13: {'description': 'Разбить список на подсписки заданной длины.',
         'example': '[1, 2, 3, 4, 5, 6, 7]; 3 → [[1, 2, 3], [4, 5, 6], [7]]',
         'type': 'list_and_number'},
    14: {'description': 'Проверить наличие дубликатов.',
         'example': '[1, 2, 3, 2] → ✅ Повторы есть; ❌ Повторов нету',
         'type': 'list_of_numbers'},
    15: {'description': 'Найти среднее арифметическое.',
         'example': '[1, 2, 3, 4, 5] → 3.0',
         'type': 'list_of_numbers'},
    16: {'description': 'Удалить минимальный элемент.',
         'example': '[5, 2, 8, 2, 1] → [5, 2, 8, 2]',
         'type': 'list_of_numbers'},
    17: {'description': 'Сдвинуть элементы вправо.',
         'example': '[1, 2, 3, 4, 5]; 6 → [4, 5, 1, 2, 3]',
         'type': 'list_and_number'},
    18: {'description': 'Посчитать уникальные элементы .',
         'example': '[1, 2, 2, 3, 4, 4, 4, 5] → 5',
         'type': 'list_of_numbers'},
    19: {'description': 'Проверить на палиндром .',
         'example': "['radar'] → ✅ Слово палиндром; ❌ Слово не палиндром",
         'type': 'list_of_words'},
    20: {'description': 'Найти пару с заданной суммой.',
         'example': '[1, 2, 3, 4, 5]; 5 → [(1, 4), (2, 3)]',
         'type': 'list_and_number'},
    21: {'description': 'Сгруппировать по длине строки.',
         'example': "['apple', 'bat', 'car', 'ant', 'orange'] → {5: ['apple'], 3: ['bat', 'car', 'ant'], 6: ['orange']}",
         'type': 'list_of_words'},
    22: {'description': 'Объединить списки без повторений и сортировкой.',
         'example': '[3, 2, 1] [2, 4, 5] [5, 6, 3] → [1, 2, 3, 4, 5, 6]',
         'type': 'list_of_numbers'},
    23: {'description': 'Найти самый длинный подряд идущий подсписок.',
         'example': '[1, 1, 2, 2, 2, 3, 3, 1, 1, 1, 1] → [1, 1, 1, 1]',
         'type': 'lists'},
    24: {'description': 'Найти элемент, встречающийся ровно один раз.',
         'example': '[4, 3, 2, 4, 1, 3, 2] → 1',
         'type': 'lists'},
    25: {'description': 'Найти все элементы в порядке возрастания частоты.',
         'example': "['a', 'b', 'c', 'a', 'b', 'a'] → ['c', 'b', 'b', 'a', 'a', 'a']",
         'type': 'list_of_words'},
    26: {'description': 'Проверить, является ли список "пилообразным".',
         'example': '[1, 3, 2, 4, 1] → ✅ Список пилообразный; ❌ Список не пилообразный',
         'type': 'lists'},
    27: {'description': 'Разделить на чётные и нечётные.',
         'example': '[1, 2, 3, 4, 5, 6] → [2, 4, 6, 1, 3, 5]',
         'type': 'lists'},
    28: {'description': 'Найти ближайшее число.',
         'example': '[10, 3, 8, 15]; 7 → 8',
         'type': 'list_and_number'},
    29: {'description': 'Найти все пары с разностью.',
         'example': '[1, 3, 5, 7]; 2 → [(1, 3), (3, 5), (5, 7)]',
         'type': 'list_and_number'},
    30: {'description': 'Сгруппировать по первому символу.',
         'example': "['apple', 'ant', 'banana', 'bee', 'cat'] → {'a': ['apple', 'ant'], 'b': ['banana', 'bee'], 'c': ['cat']}",
         'type': 'list_of_words'},
    31: {'description': 'Найти все чётные числа в списке.',
         'example': '[1, 2, 3, 4, 5, 6] → [2, 4, 6]',
         'type': 'list_of_numbers'},
    32: {'description': 'Проверить, все ли элементы списка положительные.',
         'example': '[1, 2, 3] → ✅ Все положительные\n[-1, 2, 3] → ❌ Есть отрицательные',
         'type': 'list_of_numbers'},
    33: {'description': 'Найти самое длинное слово в списке.',
         'example': "['cat', 'elephant', 'dog'] → elephant",
         'type': 'list_of_words'},
    34: {'description': 'Создать список квадратов чисел.',
         'example': '[1, 2, 3, 4] → [1, 4, 9, 16]',
         'type': 'list_of_numbers'},
    35: {'description': 'Объединить два списка в один, чередуя элементы.',
         'example': '[1, 2, 3] [10, 20] → [1, 10, 2, 20, 3]',
         'type': 'lists'},
}